### ISSUE TITLE
Photo competition for Leap 16.0 and Tumbleweed wallpaper collection

### ISSUE THREAD

**Issue by lkocman** [LelCP/wallpapers#18]
Requirements:

- [ ] Must be brand related (chameleons, chameleon-like objects, ...) alterantively resemble with a distribution logo (Leap, Tumbleweed, Slowroll)
- [ ] We need to support up to 5k (5120x3200) 16MB+/5k pictures are preferred
- [ ] Original work - submitted by the author of the photograph or with an approval from the actual author (no AI)
- [ ] Must be submitted 1st of November 2024
- [ ] Lanscape orientation only

Please copy photos including description (where was it taken and what is on the picture) as a comments into this issue. Ideally also with a link to a highres variant.

**Comment by lkocman** [comment]
![pixelcut-export](https://github.com/openSUSE/wallpapers/assets/510119/be96e93f-0245-4053-87ac-b0eaacd36c4a)
SUSE Linux 10.0 wallpaper upscaled to 4k in pixelcut. **Currently only inspirational.** Seeking approval from SUSE

**Comment by bmwiedemann** [comment]
I'd like to submit
https://photos.google.com/share/AF1QipOYjpGmphdGOR4Cf-acWWay8zc-TP2cz0V1z4W0BWxyI9phykjxV2JMEYKOTC2AaQ/photo/AF1QipNFpxbLGXl6vCs64rNGkFFpbZEBzPAZUVTxGv8z?key=WF91bzB1QW4xQllrWWYwM0NpbzR4UDlyd256Zi13

A photo I took 2024-07-08 of beech leaves with the evening sun in a German park.
Even with the lack of chameleons, it can provide a nice extra wallpaper.

![image](https://github.com/openSUSE/wallpapers/assets/510119/dee5591e-1f1e-42ad-93b2-741dbf69491e)

Also: https://photos.app.goo.gl/JrG8oJVQ8aaaH9Rk9 are all mine and I approve them as possible submission here.

**Comment by arwinneil** [comment]
Unfortunately not a chameleon, but this is :
A [Bluetail Day Gecko](https://www.inaturalist.org/observations/232226707), endemic to the small island of Mauritius. Which is also home to plenty of openSUSE enthusiast! This gecko was captured at [Ebony Forest](https://www.ebonyforest.com/), a conservation area for Mauritian endemic species with a rehabilitated indigenous forest.

Photo captured by me, and [released under public domain](https://www.inaturalist.org/photos/412551389) .

![original](https://github.com/user-attachments/assets/a464fee6-300b-41ef-8656-14ce2928b487)

Full image : [openSUSE-2024-photo-submission/DSC00902.jpg](https://github.com/arwinneil/openSUSE-2024-photo-submission/blob/main/DSC00902.jpg)

**Comment by lkocman** [comment]
@arwinneil beautiful! Many thanks! All criteria passed.

**Comment by peti** [comment]
![img-20240811-001](https://github.com/user-attachments/assets/3719ffcd-fe89-4871-9605-b9266b1cb597)

License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
Author: Peter Simons \<simons@cryp.to\>
High-resolution: https://drive.google.com/file/d/1TkyWoM4h0JqmJCFumxBMNcxajSLCWmTD/view

**Comment by peti** [comment]
![img-20240811-002](https://github.com/user-attachments/assets/841d59e9-8753-4ce9-b468-b2cdf4f8d4af)

License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
Author: Peter Simons \<simons@cryp.to\>
High-resolution: https://drive.google.com/file/d/1xazG1xGqM1iGvFWxdjpbDTgywFDf8Jz2/view

**Comment by peti** [comment]
![img-20240811-003](https://github.com/user-attachments/assets/f0014940-3e79-4c29-b08a-5c4b8075af87)

License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
Author: Peter Simons \<simons@cryp.to\>
High-resolution: https://drive.google.com/file/d/1J330m2_B5bkakO9YFpR2n_sExURmPBja/view

**Comment by peti** [comment]
![img-20240811-004](https://github.com/user-attachments/assets/cc42f1b2-4cab-4ad6-bad8-02d60d1eafc8)

License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
Author: Peter Simons \<simons@cryp.to\>
High-resolution: https://drive.google.com/file/d/1RXSg0AAHD-GA6oPgrmgqKlSoefgxTPnO/view

**Comment by ddemaio** [comment]
@peti, @arwinneil, @bmwiedemann and @lkocman 
I am wanting to highlight the efforts of those who took part in branding efforts and would like your help to tell a story about the design submissions to help highlight community contributions. This is specific to those who took part in the workshop at oSC24 and those who have submitted items for the Leap 16 branding. (https://news.opensuse.org/2024/07/09/looking-at-next-steps-for-leap-branding/) Which was done here.
We are looking for short video clips where you answer a few questions about the inspiration and reasoning behind your designs and/or submission. These clips will be part of a larger video and I’ll also use quotes from the videos for an article about branding.
Here are some questions for the video:
Tell a quick story about the photo.
What inspired the photo for the submission?
How did the chameleon theme influence your submission?
Did you consider specific elements (light/dark mode, nature, location, etc.) when creating your design? If so, what guided your decisions?
How does your design reflect the identity of openSUSE?
Be as creative as you'd like; whether you prefer to speak casually or provide a more structured response, we encourage all forms of participation.
How to Submit:
Record your video (approx. 4–5 minutes) answering the questions above.
Upload your video file to our https://demacloud.ocloud.de/index.php/s/JAmfxNkg2ZSQLtw by Oct. 18.
We’ll take it from there!
Please let me know if you have any questions.

**Comment by lkocman** [comment]
Reminder that the deadline is in two days!

**Comment by lkocman** [comment]
Many thanks to all!  We've selected [Bluetail Day Gecko](https://www.inaturalist.org/observations/232226707), which was merged as part of #19
